### ISSUE TITLE
intermittent integration issue between Pagerduty to JIRA

### ISSUE THREAD

**Issue by prabhat111** [ryanhoskin/pd2jira#12]
Hi ,

We are using pd2jira integration and its creating JIRA ticket for each PD incident, but sometimes,its unable to create JIRA ticket. 

Need to find out the reason. 

Thanks
Prabhat

**Comment by ryanhoskin** [comment]
@prabhat111 I added a line for logging.  Please test it out and let me know if it works as expected.
