### ISSUE TITLE
Error while creating JIRA ticket : Summary must be less than 255 characters

### ISSUE THREAD

**Issue by prabhat111** [ryanhoskin/pd2jira#13]
Hi,

I do see the bellow error. can you help me to modify the script.
The reason is summary has more than 255 charecters, so can you help to substr the Summary to take upto 254 characters only from the beginning. 

`A JIRA ticket failed to be created. {"errorMessages":[],"errors":{"summary":"Summary must be less than 255 characters."}}`

**Comment by ryanhoskin** [comment]
@prabhat111 - This should be fixed.
