### ISSUE TITLE
Ability to see comments from/to Jira

### ISSUE THREAD

**Issue by Mihailoff** [ryanhoskin/pd2jira#14]
Wish list item :)

**Comment by ryanhoskin** [comment]
@Mihailoff Are you saying a PagerDuty note would then get added in JIRA and vise versa?  It'd be pretty trivial to get the notes each time that the script runs each time a webhook is fired off.  Thoughts?

**Comment by Mihailoff** [comment]
Yes, exactly. The purpose of the Jira ticket is to collaborate on issue and therefore any notes from PD are valuable on Jira and vice versa.

**Comment by ryanhoskin** [comment]
@Mihailoff  - Okay.  Thanks for the clarification.  I probably won't have the bandwidth to work on this but we'll keep it in mind as we look at improving the integration.  Feel free to submit a PR if you have time to work on it.

**Comment by lfepp** [comment]
@Mihailoff I wanted to point you in the direction of the [pd_jira_bidirectional repo](https://github.com/ryanhoskin/pd_jira_bidirectional), which is a modified version of the Jira integration that now has the functionality you mentioned here. We recently updated this script to add all PagerDuty notes to the Jira ticket when an incident is resolved.
