### ISSUE TITLE
Accessbility

### ISSUE THREAD

**Issue by cnoffsin** [ryanhoskin/pd2jira#16]
Just to ask a dumb question here, this integration would assume that Pagerduty could access where-ever the p2djira php script was deployed, AND have access to https on where-ever my jira instance was too right?

Effectively meaning that my jira https was accessible outside?

**Comment by ryanhoskin** [comment]
Yes, it assumes that the script is accessible to PagerDuty as it receives a webhook from PagerDuty and uses the information passed in that request to pass along to JIRA.  You can hide it behind HTTP basic auth and include the credentials in your URL.  

Your JIRA instance will have to be accessible to wherever you host the pd2jira script, although it could be hidden from the internet.  The pd2jira script sends a POST request to your [JIRA URL](https://github.com/ryanhoskin/pd2jira/blob/master/web/pd2jira.php#L4) concatenated with `/rest/api/2/issue/`.
