### ISSUE TITLE
Jira Cloud

### ISSUE THREAD

**Issue by KISStian** [ryanhoskin/pd2jira#23]
Is this plugin compatible at all with Jira Cloud?  Thanks.

**Comment by Deconstrained** [comment]
In Jira Cloud, the same [REST API](https://developer.atlassian.com/cloud/jira/platform/rest/) is available as in Jira Server. Therefore, if you put in your Jira URL up to the end of the hostname, i.e. `https://my-company.atlassian.net`, as the `JIRA_URL` environment variable, that should be the same as doing so with Jira Server. It should thus work with Jira Cloud.
