### ISSUE TITLE
Issue in integrating pagerduty to jira

### ISSUE THREAD

**Issue by Nikhilra27** [ryanhoskin/pd2jira#6]
Hi Ryan,

I have downloaded the script for the application and filled out the variables, however i am not able to successfully have pagerduty to open tickets in jira .I am hosting the appn ,not delpoying it to heraku , i have made sure that php is installed and configured right, I am not a fan of coding or scripting , . any help to get this working would be really appreciated.

Thanks
Nikhil

**Comment by ryanhoskin** [comment]
Hey Nikhil,

Apologies for the super delayed response.  If you haven't already, please reach out to us at support@pagerduty.com and we'll be happy to help.

Cheers,
Ryan
